import type { Codicon } from './ids'

export interface IconSet {
  name: string
  display: string
  icons: Partial<Record<Codicon, string>>
}

export const set: IconSet = {
  name: 'tabler-icons',
  display: 'Tabler',
  icons: {
    'codicon:account': 'tabler:user',
    // 'codicon:activate-breakpoints': 'tabler:',
    'codicon:add': 'tabler:plus',
    'codicon:alert': 'tabler:alert-triangle',
    'codicon:archive': 'tabler:archive',
    // 'codicon:array': 'tabler:',
    'codicon:arrow-both': 'tabler:arrows-horizontal',
    'codicon:arrow-down': 'tabler:arrow-down',
    'codicon:arrow-left': 'tabler:arrow-left',
    'codicon:arrow-right': 'tabler:arrow-right',
    // 'codicon:arrow-small-down': 'tabler:',
    // 'codicon:arrow-small-left': 'tabler:',
    // 'codicon:arrow-small-right': 'tabler:',
    // 'codicon:arrow-small-up': 'tabler:',
    'codicon:arrow-swap': 'tabler:arrows-left-right',
    'codicon:arrow-up': 'tabler:arrow-narrow-up',
    'codicon:beaker': 'tabler:flask',
    'codicon:bell': 'tabler:bell',
    'codicon:bell-dot': 'tabler:bell-ringing',
    'codicon:bold': 'tabler:bold',
    'codicon:book': 'tabler:book',
    'codicon:bookmark': 'tabler:bookmark',
    'codicon:briefcase': 'tabler:briefcase',
    'codicon:broadcast': 'tabler:broadcast',
    'codicon:browser': 'tabler:browser',
    'codicon:bug': 'tabler:bug',
    'codicon:calendar': 'tabler:calendar',
    'codicon:call-incoming': 'tabler:phone-incoming',
    'codicon:call-outgoing': 'tabler:phone-outgoing',
    'codicon:case-sensitive': 'tabler:letter-case',
    'codicon:check': 'tabler:check',
    'codicon:check-all': 'tabler:checks',
    'codicon:checklist': 'tabler:list-check',
    'codicon:chevron-down': 'tabler:chevron-down',
    'codicon:chevron-left': 'tabler:chevron-left',
    'codicon:chevron-right': 'tabler:chevron-right',
    'codicon:chevron-up': 'tabler:chevron-up',
    'codicon:chrome-close': 'tabler:x',
    // 'codicon:chrome-maximize': 'tabler:',
    // 'codicon:chrome-minimize': 'tabler:',
    // 'codicon:chrome-restore': 'tabler:',
    // 'codicon:circle-filled': 'tabler:',
    // 'codicon:circle-large-filled': 'tabler:',
    // 'codicon:circle-large-outline': 'tabler:',
    // 'codicon:circle-outline': 'tabler:',
    'codicon:circle-slash': 'tabler:circle-off',
    // 'codicon:circuit-board': 'tabler:',
    'codicon:clear-all': 'tabler:clear-all',
    // 'codicon:clippy': 'tabler:',
    'codicon:clock': 'tabler:clock',
    // 'codicon:clone': 'tabler:',
    'codicon:close': 'tabler:x',
    // 'codicon:close-all': 'tabler:',
    // 'codicon:close-dirty': 'tabler:',
    'codicon:cloud': 'tabler:cloud',
    'codicon:cloud-download': 'tabler:cloud-download',
    'codicon:cloud-upload': 'tabler:cloud-upload',
    'codicon:code': 'tabler:code',
    // 'codicon:collapse-all': 'tabler:',
    'codicon:color-mode': 'tabler:contrast',
    // 'codicon:combine': 'tabler:',
    'codicon:comment': 'tabler:message',
    'codicon:comment-add': 'tabler:message-plus',
    'codicon:comment-discussion': 'tabler:messages',
    // 'codicon:compare-changes': 'tabler:compare',
    'codicon:console': 'tabler:terminal-2',
    'codicon:copy': 'tabler:copy',
    'codicon:credit-card': 'tabler:credit-card',
    'codicon:dash': 'tabler:line-dashed',
    'codicon:dashboard': 'tabler:dashboard',
    'codicon:database': 'tabler:database',
    'codicon:debug': 'tabler:bug',
    'codicon:debug-alt': 'tabler:bug',
    // 'codicon:debug-alt-small': 'tabler:',
    // 'codicon:debug-breakpoint': 'tabler:',
    // 'codicon:debug-breakpoint-conditional': 'tabler:',
    // 'codicon:debug-breakpoint-conditional-disabled': 'tabler:',
    // 'codicon:debug-breakpoint-conditional-unverified': 'tabler:',
    // 'codicon:debug-breakpoint-data': 'tabler:',
    // 'codicon:debug-breakpoint-data-disabled': 'tabler:',
    // 'codicon:debug-breakpoint-data-unverified': 'tabler:',
    // 'codicon:debug-breakpoint-disabled': 'tabler:',
    // 'codicon:debug-breakpoint-function': 'tabler:',
    // 'codicon:debug-breakpoint-function-disabled': 'tabler:',
    // 'codicon:debug-breakpoint-function-unverified': 'tabler:',
    // 'codicon:debug-breakpoint-log': 'tabler:',
    // 'codicon:debug-breakpoint-log-disabled': 'tabler:',
    // 'codicon:debug-breakpoint-log-unverified': 'tabler:',
    // 'codicon:debug-breakpoint-unsupported': 'tabler:',
    // 'codicon:debug-breakpoint-unverified': 'tabler:',
    // 'codicon:debug-console': 'tabler:',
    // 'codicon:debug-continue': 'tabler:',
    // 'codicon:debug-disconnect': 'tabler:',
    // 'codicon:debug-hint': 'tabler:',
    // 'codicon:debug-line-by-line': 'tabler:'
    // 'codicon:debug-pause': 'tabler:',
    // 'codicon:debug-rerun': 'tabler:',
    // 'codicon:debug-restart': 'tabler:',
    // 'codicon:debug-restart-frame': 'tabler:',
    // 'codicon:debug-reverse-continue': 'tabler:',
    // 'codicon:debug-stackframe': 'tabler:',
    // 'codicon:debug-stackframe-active': 'tabler:',
    // 'codicon:debug-stackframe-dot': 'tabler:',
    // 'codicon:debug-stackframe-focused': 'tabler:',
    // 'codicon:debug-start': 'tabler:',
    // 'codicon:debug-step-back': 'tabler:',
    // 'codicon:debug-step-into': 'tabler:',
    // 'codicon:debug-step-out': 'tabler:',
    // 'codicon:debug-step-over': 'tabler:',
    // 'codicon:debug-stop': 'tabler:',
    // 'codicon:desktop-download': 'tabler:',
    'codicon:device-camera': 'tabler:camera',
    'codicon:device-camera-video': 'tabler:video',
    'codicon:device-desktop': 'tabler:device-desktop',
    'codicon:device-mobile': 'tabler:device-mobile',
    // 'codicon:diff': 'tabler:',
    // 'codicon:diff-added': 'tabler:',
    // 'codicon:diff-ignored': 'tabler:',
    // 'codicon:diff-modified': 'tabler:',
    // 'codicon:diff-removed': 'tabler:',
    // 'codicon:diff-renamed': 'tabler:',
    'codicon:discard': 'tabler:arrow-back-up',
    // 'codicon:drop-down-button': 'tabler:',
    'codicon:edit': 'tabler:edit',
    // 'codicon:editor-layout': 'tabler:editor-layout',
    'codicon:ellipsis': 'tabler:line-dashed',
    // 'codicon:empty-window': 'tabler:',
    // 'codicon:error': 'tabler:circle-x',
    // 'codicon:exclude': 'tabler:',
    // 'codicon:expand-all': 'tabler:',
    'codicon:export': 'tabler:file-export',
    'codicon:extensions': 'tabler:layout-dashboard',
    'codicon:eye': 'tabler:eye',
    'codicon:eye-closed': 'tabler:eye-off',
    // 'codicon:eye-unwatch': 'tabler:',
    // 'codicon:eye-watch': 'tabler:',
    // 'codicon:feedback': 'tabler:share-knowledge',
    'codicon:file': 'tabler:file',
    'codicon:file-add': 'tabler:file-plus',
    'codicon:file-binary': 'tabler:file-digit',
    'codicon:file-code': 'tabler:file-code',
    // 'codicon:file-directory': 'tabler:',
    // 'codicon:file-directory-create': 'tabler:',
    // 'codicon:file-media': 'tabler:',
    // 'codicon:file-pdf': 'tabler:',
    // 'codicon:file-submodule': 'tabler:',
    // 'codicon:file-symlink-directory': 'tabler:',
    // 'codicon:file-symlink-file': 'tabler:',
    'codicon:file-text': 'tabler:file-text',
    'codicon:file-zip': 'tabler:file-zip',
    'codicon:files': 'tabler:files',
    'codicon:filter': 'tabler:filter',
    'codicon:filter-filled': 'tabler:filter',
    'codicon:flame': 'tabler:flame',
    'codicon:fold': 'tabler:fold',
    'codicon:fold-down': 'tabler:fold-down',
    'codicon:fold-up': 'tabler:fold-up',
    'codicon:folder': 'tabler:folder',
    // 'codicon:folder-active': 'tabler:folder-check',
    // 'codicon:folder-opened': 'tabler:',
    // 'codicon:gather': 'tabler:',
    'codicon:gear': 'tabler:settings',
    'codicon:gift': 'tabler:gift',
    'codicon:gist': 'tabler:script',
    // 'codicon:gist-fork': 'tabler:',
    // 'codicon:gist-new': 'tabler:',
    'codicon:gist-private': 'tabler:lock',
    'codicon:gist-secret': 'tabler:shield-lock',
    'codicon:git-branch': 'tabler:git-branch',
    'codicon:git-branch-create': 'tabler:git-branch',
    'codicon:git-branch-delete': 'tabler:git-branch',
    'codicon:git-commit': 'tabler:git-commit',
    'codicon:git-compare': 'tabler:git-compare',
    'codicon:git-fork-private': 'tabler:lock',
    'codicon:git-merge': 'tabler:git-merge',
    'codicon:git-pull-request': 'tabler:git-pull-request',
    // 'codicon:git-pull-request-abandoned': 'tabler:',
    // 'codicon:git-pull-request-create': 'tabler:',
    'codicon:github': 'tabler:brand-github',
    // 'codicon:github-action': 'tabler:',
    'codicon:github-alt': 'tabler:brand-github',
    // 'codicon:github-inverted': 'tabler:',
    // 'codicon:globe': 'tabler:',
    'codicon:go-to-file': 'tabler:file-symlink',
    // 'codicon:grabber': 'tabler:',
    // 'codicon:graph': 'tabler:',
    // 'codicon:graph-left': 'tabler:',
    // 'codicon:gripper': 'tabler:',
    // 'codicon:group-by-ref-type': 'tabler:',
    'codicon:heart': 'tabler:heart',
    'codicon:history': 'tabler:history',
    'codicon:home': 'tabler:home',
    // 'codicon:horizontal-rule': 'tabler:',
    'codicon:hubot': 'tabler:robot',
    'codicon:inbox': 'tabler:inbox',
    'codicon:info': 'tabler:info-circle',
    // 'codicon:issue-closed': 'tabler:',
    // 'codicon:issue-opened': 'tabler:',
    // 'codicon:issue-reopened': 'tabler:',
    // 'codicon:issues': 'tabler:',
    'codicon:italic': 'tabler:italic',
    // 'codicon:jersey': 'tabler',
    'codicon:json': 'tabler:braces',
    'codicon:kebab-horizontal': 'tabler:dots',
    'codicon:kebab-vertical': 'tabler:dots-vertical',
    'codicon:key': 'tabler:key',
    'codicon:keyboard': 'tabler:keyboard',
    // 'codicon:law': 'tabler:',
    'codicon:library': 'tabler:books',
    // 'codicon:light-bulb': 'tabler:',
    // 'codicon:lightbulb': 'tabler:bulb',
    // 'codicon:lightbulb-autofix': 'tabler:',
    'codicon:link': 'tabler:link',
    'codicon:link-external': 'tabler:external-link',
    'codicon:list-filter': 'tabler:list-search',
    'codicon:list-flat': 'tabler:list',
    'codicon:list-ordered': 'tabler:list-numbers',
    // 'codicon:list-selection': 'tabler:',
    // 'codicon:list-tree': 'tabler:',
    'codicon:list-unordered': 'tabler:list',
    'codicon:live-share': 'tabler:share',
    'codicon:loading': 'tabler:loader',
    'codicon:location': 'tabler:map-pin',
    'codicon:lock': 'tabler:lock',
    'codicon:log-in': 'tabler:login',
    'codicon:log-out': 'tabler:logout',
    'codicon:logo-github': 'tabler:brand-github',
    // 'codicon:magnet': 'tabler:',
    'codicon:mail': 'tabler:mail',
    'codicon:mail-read': 'tabler:mail-opened',
    'codicon:mail-reply': 'tabler:mail-forward',
    // 'codicon:mark-github': 'tabler:',
    // 'codicon:markdown': 'tabler:',
    // 'codicon:megaphone': 'tabler:',
    'codicon:mention': 'tabler:at',
    'codicon:menu': 'tabler:menu',
    'codicon:merge': 'tabler:git-merge',
    'codicon:microscope': 'tabler:microscope',
    'codicon:milestone': 'tabler:pennant',
    // 'codicon:mirror': 'tabler:',
    // 'codicon:mirror-private': 'tabler:',
    // 'codicon:mirror-public': 'tabler:',
    // 'codicon:more': 'tabler:',
    'codicon:mortar-board': 'tabler:school',
    'codicon:move': 'tabler:arrows-move',
    // 'codicon:multiple-windows': 'tabler:',
    // 'codicon:mute': 'tabler:',
    'codicon:new-file': 'tabler:file-plus',
    'codicon:new-folder': 'tabler:folder-plus',
    // 'codicon:no-newline': 'tabler:',
    // 'codicon:note': 'tabler:',
    // 'codicon:notebook': 'tabler:',
    // 'codicon:notebook-template': 'tabler:',
    // 'codicon:octoface': 'tabler:',
    // 'codicon:open-preview': 'tabler:',
    // 'codicon:organization': 'tabler:',
    // 'codicon:organization-filled': 'tabler:',
    // 'codicon:organization-outline': 'tabler:',
    // 'codicon:output': 'tabler:',
    // 'codicon:package': 'tabler:package',
    // 'codicon:paintcan': 'tabler:',
    'codicon:pass': 'tabler:circle-check',
    'codicon:pass-filled': 'tabler:circle-check',
    'codicon:pencil': 'tabler:pencil',
    'codicon:person': 'tabler:man',
    // 'codicon:person-add': 'tabler:w',
    // 'codicon:person-filled': 'tabler:',
    // 'codicon:person-follow': 'tabler:',
    // 'codicon:person-outline': 'tabler:',
    'codicon:pin': 'tabler:pin',
    'codicon:pinned': 'tabler:pinned',
    // 'codicon:pinned-dirty': 'tabler:',
    'codicon:play': 'tabler:player-play',
    // 'codicon:play-circle': 'tabler:',
    'codicon:plug': 'tabler:plug',
    'codicon:plus': 'tabler:plus',
    // 'codicon:preserve-case': 'tabler:',
    // 'codicon:preview': 'tabler:',
    // 'codicon:primitive-dot': 'tabler:',
    // 'codicon:primitive-square': 'tabler:',
    // 'codicon:project': 'tabler:',
    'codicon:pulse': 'tabler:activity',
    'codicon:question': 'tabler:help',
    'codicon:quote': 'tabler:quote',
    // 'codicon:radio-tower': 'tabler:',
    // 'codicon:reactions': 'tabler:',
    // 'codicon:record': 'tabler:',
    'codicon:record-keys': 'tabler:keyboard',
    'codicon:redo': 'tabler:arrow-forward-up',
    // 'codicon:references': 'tabler:',
    'codicon:refresh': 'tabler:refresh',
    'codicon:regex': 'tabler:regex',
    // 'codicon:remote': 'tabler:re',
    // 'codicon:remote-explorer': 'tabler:',
    // 'codicon:remove': 'tabler:',
    // 'codicon:remove-close': 'tabler:',
    'codicon:repl': 'tabler:terminal',
    // 'codicon:replace': 'tabler:',
    // 'codicon:replace-all': 'tabler:',
    // 'codicon:reply': 'tabler:',
    // 'codicon:repo': 'tabler:',
    // 'codicon:repo-clone': 'tabler:',
    // 'codicon:repo-create': 'tabler:',
    // 'codicon:repo-delete': 'tabler:',
    // 'codicon:repo-force-push': 'tabler:',
    // 'codicon:repo-forked': 'tabler:',
    // 'codicon:repo-pull': 'tabler:',
    // 'codicon:repo-push': 'tabler:',
    // 'codicon:repo-sync': 'tabler:',
    // 'codicon:report': 'tabler:',
    // 'codicon:request-changes': 'tabler:',
    'codicon:rocket': 'tabler:rocket',
    // 'codicon:root-folder': 'tabler:',
    // 'codicon:root-folder-opened': 'tabler:',
    'codicon:rss': 'tabler:rss',
    // 'codicon:ruby': 'tabler:',
    // 'codicon:run': 'tabler:',
    // 'codicon:run-all': 'tabler:',
    // 'codicon:run-above': 'tabler:',
    // 'codicon:run-below': 'tabler:',
    // 'codicon:save': 'tabler:',
    // 'codicon:save-all': 'tabler:',
    // 'codicon:save-as': 'tabler:',
    // 'codicon:screen-full': 'tabler:',
    // 'codicon:screen-normal': 'tabler:',
    'codicon:search': 'tabler:search',
    'codicon:search-save': 'tabler:search',
    // 'codicon:search-stop': 'tabler:',
    // 'codicon:selection': 'tabler:',
    'codicon:server': 'tabler:server',
    // 'codicon:server-environment': 'tabler:',
    // 'codicon:server-process': 'tabler:',
    'codicon:settings': 'tabler:adjustments',
    'codicon:settings-gear': 'tabler:settings',
    'codicon:shield': 'tabler:shield',
    'codicon:sign-in': 'tabler:login',
    'codicon:sign-out': 'tabler:logout',
    'codicon:smiley': 'tabler:mood-smile',
    // 'codicon:sort-precedence': 'tabler:',
    'codicon:source-control': 'tabler:git-fork',
    'codicon:split-horizontal': 'tabler:layout-columns',
    'codicon:split-vertical': 'tabler:layout-rows',
    // 'codicon:squirrel': 'tabler:',
    'codicon:star': 'tabler:star',
    'codicon:star-add': 'tabler:star',
    'codicon:star-delete': 'tabler:star',
    'codicon:star-empty': 'tabler:star',
    'codicon:star-full': 'tabler:star',
    'codicon:star-half': 'tabler:star-half',
    // 'codicon:stop': 'tabler:',
    // 'codicon:stop-circle': 'tabler:',
    // 'codicon:symbol-array': 'tabler:',
    // 'codicon:symbol-boolean': 'tabler:',
    // 'codicon:symbol-class': 'tabler:',
    // 'codicon:symbol-color': 'tabler:',
    // 'codicon:symbol-constant': 'tabler:',
    // 'codicon:symbol-constructor': 'tabler:',
    // 'codicon:symbol-enum': 'tabler:',
    // 'codicon:symbol-enum-member': 'tabler:',
    // 'codicon:symbol-event': 'tabler:',
    // 'codicon:symbol-field': 'tabler:',
    // 'codicon:symbol-file': 'tabler:',
    // 'codicon:symbol-folder': 'tabler:',
    // 'codicon:symbol-function': 'tabler:',
    // 'codicon:symbol-interface': 'tabler:',
    // 'codicon:symbol-key': 'tabler:',
    // 'codicon:symbol-keyword': 'tabler:',
    // 'codicon:symbol-method': 'tabler:',
    // 'codicon:symbol-misc': 'tabler:',
    // 'codicon:symbol-module': 'tabler:',
    // 'codicon:symbol-namespace': 'tabler:',
    // 'codicon:symbol-null': 'tabler:',
    // 'codicon:symbol-number': 'tabler:',
    // 'codicon:symbol-numeric': 'tabler:',
    // 'codicon:symbol-object': 'tabler:',
    // 'codicon:symbol-operator': 'tabler:',
    // 'codicon:symbol-package': 'tabler:',
    // 'codicon:symbol-parameter': 'tabler:',
    // 'codicon:symbol-property': 'tabler:',
    // 'codicon:symbol-reference': 'tabler:',
    // 'codicon:symbol-ruler': 'tabler:',
    // 'codicon:symbol-snippet': 'tabler:',
    // 'codicon:symbol-string': 'tabler:',
    // 'codicon:symbol-struct': 'tabler:',
    // 'codicon:symbol-structure': 'tabler:',
    // 'codicon:symbol-text': 'tabler:',
    // 'codicon:symbol-type-parameter': 'tabler:',
    // 'codicon:symbol-unit': 'tabler:',
    // 'codicon:symbol-value': 'tabler:',
    // 'codicon:symbol-variable': 'tabler:',
    'codicon:sync': 'tabler:refresh',
    'codicon:sync-ignored': 'tabler:refresh-off',
    'codicon:tag': 'tabler:tag',
    'codicon:tag-add': 'tabler:tag',
    'codicon:tag-remove': 'tabler:tag-off',
    // 'codicon:tasklist': 'tabler:',
    // 'codicon:telescope': 'tabler:',
    'codicon:terminal': 'tabler:terminal',
    // 'codicon:terminal-bash': 'tabler:',
    // 'codicon:terminal-cmd': 'tabler:',
    // 'codicon:terminal-debian': 'tabler:',
    // 'codicon:terminal-linux': 'tabler:',
    // 'codicon:terminal-powershell': 'tabler:',
    // 'codicon:terminal-tmux': 'tabler:',
    // 'codicon:terminal-ubuntu': 'tabler:',
    'codicon:text-size': 'tabler:text-size',
    // 'codicon:three-bars': 'tabler:',
    'codicon:thumbsdown': 'tabler:thumb-down',
    'codicon:thumbsup': 'tabler:thumb-up',
    'codicon:tools': 'tabler:tools',
    'codicon:trash': 'tabler:trash',
    'codicon:trashcan': 'tabler:trash-x',
    'codicon:triangle-down': 'tabler:caret-down',
    'codicon:triangle-left': 'tabler:caret-left',
    'codicon:triangle-right': 'tabler:caret-right',
    'codicon:triangle-up': 'tabler:caret-up',
    'codicon:twitter': 'tabler:brand-twitter',
    // 'codicon:type-hierarchy': 'tabler:',
    // 'codicon:type-hierarchy-sub': 'tabler:',
    // 'codicon:type-hierarchy-super': 'tabler:',
    // 'codicon:unfold': 'tabler:',
    // 'codicon:ungroup-by-ref-type': 'tabler:',
    'codicon:unlock': 'tabler:lock-open',
    // 'codicon:unmute': 'tabler:',
    // 'codicon:unverified': 'tabler:',
    // 'codicon:variable': 'tabler:',
    // 'codicon:verified': 'tabler:',
    'codicon:versions': 'tabler:versions',
    // 'codicon:vm': 'tabler:',
    // 'codicon:vm-active': 'tabler:',
    // 'codicon:vm-connect': 'tabler:',
    // 'codicon:vm-outline': 'tabler:',
    // 'codicon:vm-running': 'tabler:',
    'codicon:wand': 'tabler:wand',
    'codicon:warning': 'tabler:alert-triangle',
    'codicon:watch': 'tabler:device-watch',
    // 'codicon:whitespace': 'tabler:',
    // 'codicon:whole-word': 'tabler:',
    // 'codicon:window': 'tabler:',
    // 'codicon:word-wrap': 'tabler:',
    // 'codicon:wrench': 'tabler:',
    // 'codicon:wrench-subaction': 'tabler:',
    // 'codicon:x': 'tabler:',
    // 'codicon:zap': 'tabler:',
    'codicon:zoom-in': 'tabler:zoom-in',
    'codicon:zoom-out': 'tabler:zoom-out',
  },
}
